template_path: templates/lucee-eb-example.yaml
parameters:
  AvailabilityZones: us-east-1c,us-east-1d
  BucketName: {{ var.bucket_name }}
  KeyName: {{ var.key_name }}
  AllowedIP: {{ var.allowed_ip_cidr }}
  Version: {{ var.version }}